# -*- coding: utf-8 -*-
"""testando VROv2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xcsr9w6pRLZrKjbO5_Kz2VJtvBWg7x7

# Instalar bibliotecas
"""

#!pip install -q streamlit pyngrok pandas
#!pip install streamlit-card
#!pip install streamlit-autorefresh

"""# Layout"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import sqlite3
# import streamlit as st
# from streamlit_autorefresh import st_autorefresh
# 
# st.set_page_config(
#     page_title="VRO",
#     layout="wide",
#     initial_sidebar_state="collapsed"
# )
# 
# 
# # ==============================
# # Banco
# # ==============================
# conn = sqlite3.connect("db.db", check_same_thread=False)
# c = conn.cursor()
# 
# c.execute("""
# CREATE TABLE IF NOT EXISTS ideas
# (id INTEGER PRIMARY KEY, autor TEXT, problema TEXT, impacto TEXT, solucao TEXT, monetizado TEXT)
# """)
# 
# c.execute("""
# CREATE TABLE IF NOT EXISTS votes
# (user TEXT, idea_id INTEGER)
# """)
# 
# conn.commit()
# 
# # ==============================
# # Estado
# # ==============================
# if "selected_votes" not in st.session_state:
#     st.session_state.selected_votes = []
# 
# if "show_new_postit" not in st.session_state:
#     st.session_state.show_new_postit = False
# 
# # ==============================
# # Funções
# # ==============================
# def get_ideas():
#     return c.execute("SELECT * FROM ideas ORDER BY id DESC").fetchall()
# 
# def get_vote_counts():
#     rows = c.execute("""
#         SELECT idea_id, COUNT(*) as total
#         FROM votes
#         GROUP BY idea_id
#         ORDER BY total DESC, idea_id ASC
#     """).fetchall()
#     return {row[0]: row[1] for row in rows}
# 
# def toggle_vote(idea_id):
#     current = st.session_state.selected_votes.copy()
#     if idea_id in current:
#         current.remove(idea_id)
#     else:
#         if len(current) < 3:
#             current.append(idea_id)
#     st.session_state.selected_votes = current
# 
# def save_votes(user_name):
#     c.execute("DELETE FROM votes WHERE user=?", (user_name,))
#     for v in st.session_state.selected_votes:
#         c.execute("INSERT INTO votes VALUES (?,?)", (user_name, v))
#     conn.commit()
# 
# def user_has_voted(user_name):
#     row = c.execute(
#         "SELECT COUNT(*) FROM votes WHERE user=?",
#         (user_name,)
#     ).fetchone()
#     return row[0] > 0
# 
# def get_top_map(ideas, vote_counts):
#     ranking_ids = sorted(
#         [idea[0] for idea in ideas],
#         key=lambda x: vote_counts.get(x, 0),
#         reverse=True
#     )
#     return {iid: pos for pos, iid in enumerate(ranking_ids[:3], start=1)}
# 
# def get_card_bg(i, selected=False):
#     palette = ["#FFF7D6", "#EAF6E3", "#E9F2FB", "#FFF1E6", "#F7ECF5"]
#     if selected:
#         return "#DFF7E8"
#     return palette[i % len(palette)]
# 
# def get_border(top_pos=None, selected=False):
#     if selected:
#         return "#22c55e"
#     if top_pos == 1:
#         return "#eab308"
#     if top_pos == 2:
#         return "#6366f1"
#     if top_pos == 3:
#         return "#ec4899"
#     return "#dbe4ee"
# 
# def badge_text(top_pos=None, selected=False):
#     badges = []
#     if selected:
#         badges.append("Votado")
#     else:
#         if top_pos == 1:
#             badges.append("Top 1")
#         elif top_pos == 2:
#             badges.append("Top 2")
#         elif top_pos == 3:
#             badges.append("Top 3")
#     return " • ".join(badges)
# 
# # ==============================
# # CSS GLOBAL
# # ==============================
# st.markdown("""
# <style>
# header {visibility: hidden; height: 0px !important;}
# #MainMenu {visibility: hidden;}
# footer {visibility: hidden;}
# 
# .stApp {
#     background: #f4f7fb;
#     margin-top: -18px;
# }
# 
# .block-container {
#     max-width: 100% !important;
#     padding-top: 0rem !important;
#     padding-bottom: 2rem !important;
#     padding-left: 1rem !important;
#     padding-right: 1rem !important;
# }
# 
# section.main > div {
#     padding-top: 0rem !important;
# }
# 
# .hero {
#     background: #f4f7fb;
#     padding: 18px 8px 8px 8px;
#     margin-bottom: 0.8rem;
# }
# 
# .main-title {
#     text-align: center;
#     font-size: 2rem;
#     font-weight: 800;
#     color: #0f172a;
#     margin-bottom: 0.1rem;
#     letter-spacing: -0.02em;
# }
# 
# .sub-title {
#     text-align: center;
#     color: #475569;
#     font-size: 0.98rem;
#     margin-bottom: 0.2rem;
# }
# 
# label, .stTextInput label, .stTextArea label {
#     color: #0f172a !important;
#     font-weight: 700;
# }
# 
# .stTextInput input,
# .stTextArea textarea {
#     color: #0f172a !important;
#     background-color: #ffffff !important;
#     border: 1px solid #cbd5e1 !important;
#     border-radius: 14px !important;
# }
# 
# .stTextInput input:focus,
# .stTextArea textarea:focus {
#     border: 1px solid #1e3a8a !important;
#     box-shadow: 0 0 0 1px #1e3a8a !important;
# }
# 
# .stTabs [data-baseweb="tab-list"] {
#     gap: 8px;
# }
# 
# .stTabs [data-baseweb="tab"] {
#     background: rgba(255,255,255,0.9);
#     border-radius: 14px 14px 0 0;
#     border: 1px solid rgba(15,23,42,0.06);
#     padding: 10px 16px;
#     color: #0f172a !important;
#     font-weight: 600;
# }
# 
# .stTabs [aria-selected="true"] {
#     color: #0f172a !important;
# }
# 
# .helper {
#     color: #475569;
#     font-size: 0.95rem;
#     margin-bottom: 1rem;
# }
# 
# .metric-box {
#     background: rgba(255,255,255,0.92);
#     border: 1px solid rgba(15,23,42,0.06);
#     border-radius: 16px;
#     padding: 12px 16px;
#     margin-bottom: 14px;
#     color: #334155;
# }
# 
# .rank-box {
#     background: #ffffff !important;
#     border: 1px solid rgba(15,23,42,0.10);
#     border-radius: 16px;
#     padding: 14px 16px;
#     margin-bottom: 10px;
#     color: #0f172a !important;
#     font-weight: 600;
# }
# 
# .rank-box * {
#     color: #0f172a !important;
# }
# 
# h1, h2, h3, h4, p, span, div {
#     color: #0f172a;
# }
# 
# .card-shell, .new-postit-shell {
#     border-radius: 20px;
#     padding: 14px;
#     min-height: 320px;
#     margin-bottom: 10px;
#     box-shadow: 0 8px 20px rgba(15,23,42,0.07);
# }
# 
# .new-postit-shell {
#     background: #FFF7D6;
#     border: 2px solid #eab308;
#     min-height: auto;
#     margin-bottom: 18px;
# }
# 
# .card-meta {
#     display: flex;
#     justify-content: space-between;
#     align-items: center;
#     gap: 8px;
#     margin-bottom: 8px;
# }
# 
# .card-chip {
#     display: inline-block;
#     padding: 4px 10px;
#     border-radius: 999px;
#     font-size: 0.73rem;
#     font-weight: 700;
#     background: rgba(255,255,255,0.72);
#     border: 1px solid rgba(15,23,42,0.06);
#     color: #0f172a;
# }
# 
# .card-title {
#     font-size: 1.08rem;
#     font-weight: 800;
#     color: #0f172a;
#     margin-bottom: 2px;
# }
# 
# .section-label {
#     font-size: 0.8rem;
#     font-weight: 800;
#     color: #334155;
#     margin-top: 10px;
#     margin-bottom: 2px;
# }
# 
# .section-text {
#     font-size: 0.92rem;
#     color: #0f172a;
#     line-height: 1.38;
# }
# 
# /* botão principal (Confirmar votos) */
# .stButton > button {
#     width: 100% !important;
#     min-height: 46px !important;
#     height: 46px !important;
#     border-radius: 12px !important;
#     font-weight: 700 !important;
#     font-size: 0.95rem !important;
# 
#     background-color: #0f172a !important;
#     color: #ffffff !important;
# 
#     border: none !important;
# 
#     display: flex !important;
#     align-items: center !important;
#     justify-content: center !important;
# 
#     -webkit-text-fill-color: #ffffff !important; /* ESSA LINHA resolve no mobile */
# }
# 
# /* força qualquer texto interno ficar branco */
# .stButton > button * {
#     color: #ffffff !important;
# }
# 
# /* hover */
# .stButton > button:hover {
#     background-color: #1e293b !important;
# }
# 
# .stButton > button:disabled {
#     background-color: #cbd5e1 !important;
#     color: #0f172a !important;
#     border: 1px solid #cbd5e1 !important;
# }
# 
# .stCheckbox label, .stCheckbox span {
#     color: #0f172a !important;
#     font-weight: 700 !important;
# }
# 
# div[data-testid="stAlert"], div[data-testid="stAlert"] * {
#     color: #0f172a !important;
# }
# 
# div[data-testid="stForm"] {
#     background: #FFF7D6 !important;
#     border: 2px solid #eab308 !important;
#     border-radius: 22px !important;
#     padding: 20px !important;
#     box-shadow: 0 8px 20px rgba(15,23,42,0.08) !important;
#     margin-bottom: 18px !important;
# }
# 
# div[data-testid="stForm"] h3 {
#     color: #0f172a !important;
#     font-weight: 800;
# }
# 
# div[data-testid="stForm"] textarea {
#     background-color: #FFF7D6 !important;
#     color: #0f172a !important;
#     border: 1px solid #eab308 !important;
#     border-radius: 14px !important;
# }
# 
# div[data-testid="stForm"] textarea:focus {
#     border: 1px solid #d97706 !important;
#     box-shadow: 0 0 0 1px #d97706 !important;
# }
# 
# @media (max-width: 768px) {
#     .card-shell {
#         min-height: 280px;
#         padding: 12px;
#     }
#     .main-title {
#         font-size: 1.7rem;
#     }
# }
# 
# 
# /* Corrige texto do checkbox de votação */
# div[data-testid="stCheckbox"] label,
# div[data-testid="stCheckbox"] label span,
# div[data-testid="stCheckbox"] p {
#     color: #0f172a !important;
#     font-weight: 700 !important;
#     opacity: 1 !important;
# }
# 
# /* Corrige chip dentro do post-it */
# .card-chip {
#     min-width: auto !important;
#     max-width: none !important;
#     white-space: nowrap !important;
#     overflow: visible !important;
#     color: #0f172a !important;
# }
# </style>
# """, unsafe_allow_html=True)
# 
# # ==============================
# # Header
# # ==============================
# st.markdown("""
# <div class="hero">
#     <div class="main-title">VRO - Value Realization Office</div>
#     <div class="sub-title">Idea Prioritization Board</div>
# </div>
# """, unsafe_allow_html=True)
# 
# name = st.text_input("Seu nome")
# 
# tab1, tab2, tab3, tab4 = st.tabs(["Ideias", "Votação", "Resultado", "Projetar"])
# 
# modo_telao = st.checkbox("Modo Projetar: atualizar automaticamente")
# 
# if modo_telao:
#     st_autorefresh(interval=1000, key="auto_refresh")
# 
# # ==============================
# # Função de exibição do card
# # ==============================
# def show_card(idea, idx, vote_count=0, selected=False, top_pos=None):
#     idea_id, autor, problema, impacto, solucao, monetizado = idea
#     bg = get_card_bg(idx, selected=selected)
#     border = get_border(top_pos=top_pos, selected=selected)
#     badge = badge_text(top_pos=top_pos, selected=selected)
# 
#     badge_html = f'<span class="card-chip">{badge}</span>' if badge else ""
# 
#     card_html = f"""<div class="card-shell" style="background:{bg}; border:2px solid {border};">
# <div class="card-meta">
# <div>{badge_html}</div>
# <div><span class="card-chip">{vote_count} voto(s)</span></div>
# </div>
# <div class="card-title">Ideia {idea_id}</div>
# <div class="section-label">1 - Problema Inicial</div>
# <div class="section-text">{problema}</div>
# <div class="section-label">2 - Impactados pelo problema</div>
# <div class="section-text">{impacto}</div>
# <div class="section-label">3 - Hipótese de Solução</div>
# <div class="section-text">{solucao}</div>
# <div class="section-label">4 - Resultado/Impacto [Monetizado]</div>
# <div class="section-text">{monetizado}</div>
# </div>"""
# 
#     st.markdown(card_html, unsafe_allow_html=True)
# 
# # ==============================
# # TAB 1 - Ideias
# # ==============================
# with tab1:
#     st.markdown(
#         '<div class="helper">Clique em “Adicionar post-it” para criar uma nova ideia.</div>',
#         unsafe_allow_html=True
#     )
# 
#     if st.button("+ Adicionar post-it", use_container_width=True):
#         st.session_state.show_new_postit = True
# 
#     if st.session_state.show_new_postit:
#         with st.form("novo_postit_form", clear_on_submit=True):
#             st.markdown("### Novo post-it")
# 
#             problema = st.text_area("1 - Problema Inicial", key="novo_problema")
#             impacto = st.text_area("2 - Impactados pelo problema", key="novo_impacto")
#             solucao = st.text_area("3 - Hipótese de Solução", key="nova_solucao")
#             monetizado = st.text_area("4 - Resultado/Impacto [Monetizado]", key="novo_monetizado")
# 
#             salvar = st.form_submit_button("Salvar post-it", use_container_width=True)
# 
#             if salvar:
#                 if name and problema and impacto and solucao and monetizado:
#                     c.execute(
#                         "INSERT INTO ideas (autor, problema, impacto, solucao, monetizado) VALUES (?,?,?,?,?)",
#                         (name, problema, impacto, solucao, monetizado)
#                     )
#                     conn.commit()
#                     st.session_state.show_new_postit = False
#                     st.success("Post-it salvo com sucesso.")
#                     st.rerun()
#                 else:
#                     st.error("Preencha seu nome e os 4 campos do post-it.")
# 
#         if st.button("Cancelar", use_container_width=True):
#             st.session_state.show_new_postit = False
#             st.rerun()
# 
#     ideias = get_ideas()
#     vote_counts = get_vote_counts()
# 
#     st.markdown("### Mural")
#     if not ideias:
#         st.info("Ainda não há ideias cadastradas.")
#     else:
#         top_map = get_top_map(ideias, vote_counts)
#         cols = st.columns(3)
# 
#         for i, idea in enumerate(ideias):
#             idea_id = idea[0]
#             with cols[i % 3]:
#                 show_card(
#                     idea=idea,
#                     idx=i,
#                     vote_count=vote_counts.get(idea_id, 0),
#                     selected=False,
#                     top_pos=top_map.get(idea_id)
#                 )
# 
# # ==============================
# # TAB 2 - Votação
# # ==============================
# with tab2:
#     st.markdown(
#         '<div class="helper">Selecione até 3 ideias marcando a opção abaixo de cada card.</div>',
#         unsafe_allow_html=True
#     )
# 
#     ideias = get_ideas()
#     vote_counts = get_vote_counts()
# 
#     if not ideias:
#         st.info("Ainda não há ideias para votar.")
#     elif not name:
#         st.warning("Digite seu nome antes de votar.")
#     else:
#         ja_votou = user_has_voted(name)
# 
#         top_map = get_top_map(ideias, vote_counts)
#         cols = st.columns(3)
# 
#         for i, idea in enumerate(ideias):
#             idea_id = idea[0]
#             is_selected = idea_id in st.session_state.selected_votes
# 
#             with cols[i % 3]:
#                 show_card(
#                     idea=idea,
#                     idx=i,
#                     vote_count=vote_counts.get(idea_id, 0),
#                     selected=is_selected,
#                     top_pos=top_map.get(idea_id)
#                 )
# 
#                 novo_valor = st.checkbox(
#                     "Votar",
#                     value=is_selected,
#                     key=f"check_{idea_id}",
#                     disabled=ja_votou or (not is_selected and len(st.session_state.selected_votes) >= 3)
#                 )
# 
#                 if not ja_votou:
#                     if novo_valor and idea_id not in st.session_state.selected_votes:
#                         toggle_vote(idea_id)
#                         st.rerun()
# 
#                     if not novo_valor and idea_id in st.session_state.selected_votes:
#                         toggle_vote(idea_id)
#                         st.rerun()
# 
#         st.markdown("---")
# 
#         if len(st.session_state.selected_votes) == 3:
#             st.info("Você atingiu o limite máximo de 3 ideias.")
# 
#         if ja_votou:
#             st.success("Seus votos já foram computados.")
#             st.button("Votos confirmados", use_container_width=True, disabled=True)
#         else:
#             if st.button(
#                 "Confirmar votos",
#                 use_container_width=True,
#                 disabled=(not name or len(st.session_state.selected_votes) == 0)
#             ):
#                 save_votes(name)
#                 st.success("Votos registrados com sucesso.")
#                 st.rerun()
# 
# # ==============================
# # TAB 3 - Resultado
# # ==============================
# with tab3:
#     ideias = get_ideas()
#     vote_counts = get_vote_counts()
# 
#     if not ideias:
#         st.info("Ainda não há ideias cadastradas.")
#     elif not vote_counts:
#         st.info("Ainda não há votos.")
#     else:
#         ranking = sorted(vote_counts.items(), key=lambda x: x[1], reverse=True)
# 
# 
# 
#         st.markdown("### Ideias em destaque")
#         cols = st.columns(3)
# 
#         for idx, (idea_id, votos) in enumerate(ranking[:3], start=1):
#             idea = c.execute("SELECT * FROM ideas WHERE id=?", (idea_id,)).fetchone()
#             with cols[(idx - 1) % 3]:
#                 show_card(
#                     idea=idea,
#                     idx=idx - 1,
#                     vote_count=votos,
#                     selected=False,
#                     top_pos=idx
#                 )
# 
#         st.markdown(
#             '<h3 style="color:#0f172a; font-weight:800;">Ranking</h3>',
#             unsafe_allow_html=True
#         )
#         for pos, (idea_id, votos) in enumerate(ranking, start=1):
#             idea = c.execute("SELECT * FROM ideas WHERE id=?", (idea_id,)).fetchone()
#             medal = "1º" if pos == 1 else "2º" if pos == 2 else "3º" if pos == 3 else f"{pos}º"
#             st.markdown(
#                 f'<div class="rank-box"><b>{medal}</b> Ideia {idea[0]} — {idea[4]} <span style="float:right;"><b>{votos}</b> voto(s)</span></div>',
#                 unsafe_allow_html=True
#             )

"""# Ignorar"""

from pyngrok import ngrok
import time

ngrok.set_auth_token("3Cibw8lkFZen3c8Rr3tIRgTQqpT_2XraastL8ztGCqQaaBumZ")

try:
    ngrok.kill()
except:
    pass

public_url = ngrok.connect(8501)
print("LINK DO APP:", public_url)

get_ipython().system_raw("streamlit run app.py --server.port 8501 &")
time.sleep(5)
print("App iniciado.")

"""# Apagar as ideias"""

import os

if os.path.exists("db.db"):
    os.remove("db.db")
    print("Banco apagado.")
else:
    print("Banco não encontrado.")

"""# Rodar após atualizar layout"""

!pkill -f streamlit || true
get_ipython().system_raw("streamlit run app.py --server.port 8501 &")